#!/usr/bin/env bash

# remove emacs files that interfere with flake8
find -name '.\#*' -exec rm {} \;
find -name '\#*\#' -exec rm {} \;


flake8 --exit-zero --statistics

flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
if [ $? -ne 0 ]; then
  exit 1
fi